### ISSUE TITLE
Create animated/static habitat maps

### ISSUE THREAD

**Issue by kstierhoff** [nmfs-swfsc-ast/ast-tasks#104]
Generate habitat maps for 2024 survey (one for Lasker, one for LM/LBC).

![Image](https://github.com/user-attachments/assets/ac8bd06b-ec39-4fec-9090-1eded7695d3b)

![Image](https://github.com/user-attachments/assets/88f122c2-dcca-4ac7-8f7c-7d7c059b22e0)

**Comment by jrenfree** [comment]
I'm on it!

**Comment by jrenfree** [comment]
Just to confirm, you want a separate plot for Lasker and another for LM+LBC? I think we did separate plots last year because of the large time difference between vessels

**Comment by kstierhoff** [comment]
Given the synchronicity of sampling this year, we could use one image, unless the Lasker transect lines obscured the nearshore transects.

**Comment by jrenfree** [comment]
![Image](https://github.com/user-attachments/assets/d511abd3-a445-472d-a8d1-6973573d6254)

**Comment by kstierhoff** [comment]
Much obliged!
