### ISSUE TITLE
Remove duplicate CTD casts from RL SCS data

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#16]
Duplicate button presses exist for CTD casts in the .elg files. Should be 7 casts. Remove button presses where Notes field is NA.

**Comment by jrenfree** [comment]
I know that this is an existing issue in the estimATM repository, but thought I'd make one here as well for easier tracking within the AST project.

**Comment by jrenfree** [comment]
@kstierhoff I'll plan to try and tackle this for now in a new estimATM branch.

**Comment by jrenfree** [comment]
Well the UCTD data doesn't contain GPS data, and it doesn't appear that anyone filled out the UCTD info in the electronic log book, so it looks like the SCS data might be our best bet.

Any other ideas?

**Comment by kstierhoff** [comment]
I actually instructed folks to not enter GPS data into the cast files. It's tedious and error prone, IMO. Maybe a good backup option. Instead, I merge the cast files with the nav data from ERDDAP. I think this is the time to create a subroutine for processing casts, and be used in various places (eg plotCTD, and elsewhere). This code is correctly duplicated and should be consolidated. Let's discuss how best to tackle it. I have some ideas.

**Comment by jrenfree** [comment]
Do you want to tackle that? It certainly seems like the code in plotCTD.Rmd can be reused, but reportSurvey should not be dependent on plotCTD being run first.

Perhaps either input the necessary parts directly into reportSurvey or create a separate script/function that gets called by both plotCTD and reportSurvey?

**Comment by kstierhoff** [comment]
Yes, I can tackle that. I plan to put the processing code from plotCTD into a subroutine that extracts nav data from ERDDAP or SCS for the time period in the cast files. It will be stand-alone. Sound good?

**Comment by jrenfree** [comment]
Sounds good. I'll go ahead and delete the branch I had created.

**Comment by jrenfree** [comment]
Kevin added some new scripts that get called by reportSurvey and plotCTD, which reads the (U)CTD headers and data.

**Comment by kstierhoff** [comment]
Kevin is the bestest.
