### ISSUE TITLE
Formatting of NASC/CUFES/TRAWL Figure from reportSurvey

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#17]
@kstierhoff , can you help me with the formatting of the following figure? After I separated out the catches from Lasker and Lisa Marie, the figure labels (a,b,c,d) seem off. I'm also wondering if we should add titles to the catch maps to indicate which one is from Lasker and which one for Lisa Marie, but I suppose that could be specific in the figure caption.

![Screenshot 2022-11-23 161017](https://user-images.githubusercontent.com/8889568/203666911-553bf308-c876-4d14-b805-d5cccef0c285.png)

**Comment by jrenfree** [comment]
Fixed the subplot labels by fixing the width definition in the ggsave command.

![Screenshot 2022-11-28 083041](https://user-images.githubusercontent.com/8889568/204330584-0d40242c-8d78-4fe2-b952-4d8eddbf840c.png)

Should I also add "Lasker" and "Carnage" titles to the two right-most plots, or just specify them in the figure caption? If the former, do you know how to do that without messing up the subplot heights?

**Comment by kstierhoff** [comment]
I think you could just specify in the legend. If you add titles to c and d, you could use the[ annotate function](https://ggplot2.tidyverse.org/reference/annotate.html) in ggplot, but it might get complicated given how  these plots are generated. I could help with that if you'd like to pursue it. I'd also make a note in the caption saying that CUFES (b) is only from Lasker (which explains the lack of data further north).

**Comment by jrenfree** [comment]
Feel free to take a stab at it. If too complicated then let's not worry about it and just describe it in the caption.

**Comment by kstierhoff** [comment]
I added annotations to the Figure. Looks like this. Thoughts?
![fig_nasc_cufes_haul_wt](https://user-images.githubusercontent.com/2256746/204371469-add00025-d4c8-49c2-9880-5340acd1924c.png)

**Comment by jrenfree** [comment]
Is it possible to position the label on top of the figure, i.e., next to c) and d)?

**Comment by kstierhoff** [comment]
Anything is possible, @jrenfree, it's just how much time you want to invest! Kidding, I'll take a stab using {cowplot}.

**Comment by kstierhoff** [comment]
Which option do you prefer? I didn't commit these in code, but I can implement whichever one you prefer.

![fig_nasc_cufes_haul_wt](https://user-images.githubusercontent.com/2256746/204373267-ff0d9db2-70d8-41d5-8215-1bf34317a568.png)

**Comment by jrenfree** [comment]
Ooof tough call. I think I prefer the label on top of the figure, but perhaps centered and not directly next to the subplot label

**Comment by kstierhoff** [comment]
I'll commit the changes for the cowplot option. I'll take a stab at adding spaces to center the label over the panel, and you can tweak it as necessary.

**Comment by kstierhoff** [comment]
Restored original code options. Left annotation code but commented-out, in case we want to revisit it.
