### ISSUE TITLE
2021 Saildrone Data

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#19]
When plotting the Saildrone CSVs files, it appears that there are some odd-looking transects:
![Screenshot 2022-11-28 164515](https://user-images.githubusercontent.com/8889568/204410740-d90fdb78-e88e-42d4-8e6c-862b88cbcc6b.png)

It appears that the southernmost odd transect is 109 from SD-1055. However, when I load the EV file for that transect, the GPS data does not appear correct, as it shows a gap in the data at that transect and interpolates that the ship goes over land:
![Screenshot 2022-11-28 164647](https://user-images.githubusercontent.com/8889568/204410902-ab6f2e02-5786-4fd8-87cf-3d0f445fbbe4.png)

If I then load the same GPS csv file in Matlab and plot that, the GPS data looks correct:
![2107SD](https://user-images.githubusercontent.com/8889568/204411024-0991e1eb-ec68-4384-b0df-de3ddfef0b71.png)

For now it appears to me that the process CSV files are fine, but for some reason Echoview is not correctly loading the GPS data at the moment. It does seems like transect 109 from SD-1055 is erroneous, and is likely a transit that got interpreted as a transect.

Will need to investigate more the partial transit on the western end of transect 121 conducted by SD-1059.

**Comment by kstierhoff** [comment]
@jrenfree, it's not clear to me that there is a task associated with this issue. I'm available today to explore this with you, if needed. I agree that it appears that at least one transect (121?) has an offshore tail that should be removed.

**Comment by jrenfree** [comment]
It was a minor comment on a separate task that you made after getting revisions back from Roger for the biomass report. I didn't want it to get buried in some random comment so I made a new task for it.

**Comment by jrenfree** [comment]
I reloaded Transect SD1055_109 in Echoview 13 on my local PC and it indeed appears that it is that diagonal line, so I think we should plan to exclude this transect from any analysis:
![image](https://user-images.githubusercontent.com/8889568/209203788-19e4b786-ee8a-452f-a8bd-b8caadba9463.png)

For Transect SD1059_121, it indeed appears that a section of the transit south on the western end was included. I reprocessed this line and ran it back through NASC(R), and put the results on the AST3 drive:

X:\SURVEYS\20210702_SAILDRONE_SummerCPS\PROCESSED\EV\CSV\SD1059\CPSFilter_-13dB\POST-PROCESSED

**Comment by jrenfree** [comment]
Re-opening, as Transect 121 isn't plotting properly on the habitat map, so need to determine which portion of it is incorrect.

**Comment by jrenfree** [comment]
Transect 121 is now confirmed to be good, however:

- Transect 117 (entirely sampled by SD1059) appears to include an erroneous diagonal portion, and
- Transect 115 appears to be missing the offshore section sampled by SD1059

Will work on correcting these.

**Comment by jrenfree** [comment]
Fixed Transect 117, and I believe the offshore portion of Transect 115 is missing because that's when SD1059 encountered hardware issues and had to come in. So I believe all should be fixed now, and latest files are on AST3.

Here is the most up-to-date habitat map:
![fig_summer2021_habitat](https://user-images.githubusercontent.com/8889568/209282961-41b20c73-f1ba-47bc-ad97-515dc08a0200.png)

**Comment by kstierhoff** [comment]
I think I see these files on AST3, but I'm not readily finding the nasc_cps.csv versions. Have they been re-run through the R script or has the mask been applied otherwise?

**Comment by jrenfree** [comment]
For each Saildrone, the files you should use are in:

CPSFilter_-13dB\POST-PROCESSED

**Comment by kstierhoff** [comment]
Thank you, I've updated my file set.
