### ISSUE TITLE
SRP-Mexico

### ISSUE THREAD

**Issue by kstierhoff** [nmfs-swfsc-ast/ast-tasks#2]
Develop and submit documents for Mexican SRP.

**Comment by kstierhoff** [comment]
- [x] Request letters of support from INAPESCA
- [x] Contact MOC-A (e.g., Gallagher)
- [x] Participant list
- [x] CVs for list of SWFSC participants
- [x] CVs for list of INAPESCA participants
- [x] Send SWFSC documents to Gallagher and Burrill via Kiteworks
- [x] Upload to RATS
- [x] Submit to State

**Comment by stevesessions** [comment]
2023 CCES Mexico Research Permit application documents sent to Capt. Gallagher and Derek Burrill via Kiteworks.

**Comment by kstierhoff** [comment]
@stevesessions Reopening with a note to add Brad Erisman to list of participants. Not sure if he was on the previous list; if so, this can be closed again and moved to completed in the Project.

**Comment by kstierhoff** [comment]
Docs for B. Erisman have been provided to MOC-A.

**Comment by kstierhoff** [comment]
Reopening until confirmation that docs have been uploaded to RATS and submitted to State.

**Comment by kstierhoff** [comment]
Documents have been transmitted to the U.S. Embassy in Mexico City, per email from Gabby David on 1/12/2023.
