### ISSUE TITLE
Add LM and LBC catch data to Appendix C in Survey Report

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#22]
Right now I believe only Lasker data is included in Appendix C. Update this to also include seine data from Lisa Marie and Long Beach Carnage.

**Comment by kstierhoff** [comment]
I need to:
- [x] examine the settings for seine.vessels (currently only has "LBC")
- [x] which removes them from set.summ.wt and set.pie (probably what we want)
- [x] look to see if LM data are included in the trawl summary table (I think they are)
- [x] determine whether we want to lump the LM data with RL, or create a separate table for LM and LBC seine catch...
- [x] if we lump RL and LM, we should probably add a column for vessel name, and rename the table something other than Trawl catch summary...

Do you have a gut feeling of the best approach, @jrenfree?

**Comment by kstierhoff** [comment]
Incorporated LM and LBC seine summary data to two appendices, one for each vessel. Did so by:

- Adding "LM" to seine.vessels
- Creating a new seine.summ data frame after sourcing processSeine_2207RL.
- Added two new code chunks to the Appendix to filter and format the set data.

Made some additional changes to processSeine to format the dates and times to be consistent with the trawl summary table.

Made slight change to pie.radius.ns to make pies a better size in the LBC seine catch plot.
