### ISSUE TITLE
Draft Project Instructions-2307RL

### ISSUE THREAD

**Issue by kstierhoff** [nmfs-swfsc-ast/ast-tasks#24]
Revise [draft Project Instructions on Google Drive](https://docs.google.com/document/d/1r7jkrHRP5-Bl0fEAYB_9-xnAtMKnx4IdDTf4U16GTf8/edit#)

**Comment by kstierhoff** [comment]
- [x] Update leg dates and port call locations
- [x] Update survey plan map
- [x] Update waypoint tables
- [x] Develop nearshore sampling plan for LBC
- [x] Develop nearshore sampling plan for LM
- [x] Develop sampling plan for Saildrones (180 mission days; 3 USVs)
- [x] Determine schedule for NWFSC-SH
- [x] Determine schedule for INAPESCA-JCF
- [x] Update staffing plan (see [Google Sheet](https://docs.google.com/spreadsheets/d/1ciECeldoZzOimixoTVpzqx6wtzs23m44NozWPTSlVhs/edit#gid=0))

**Comment by alicebeittel** [comment]
Made some edits and suggestions to the project instructions. X-Ray Protocol is revised and inserted into project instructions.

**Comment by kstierhoff** [comment]
A few final items to wrap-up the PIs:

- [x] Update waypoint tables for RL (after adding add'l compulsory transects)
- [x] Revise regional sampling plan
- [x] Incorporate guidance from Icelandic ship captains into arced-tow SOP
- [x] Finalize staffing plan
- [x] Incorporate edits from RL CO and crew

**Comment by kstierhoff** [comment]
Project instructions have been circulated to SWFSC DO and MOC-P for final signatures.
