### ISSUE TITLE
Platform Communications Plan

### ISSUE THREAD

**Issue by alicebeittel** [nmfs-swfsc-ast/ast-tasks#40]

**Comment by alicebeittel** [comment]
@kstierhoff @ddemer @jpzwolinski @jrenfree @dmurfin @stevesessions @ScottMau 

Hi All, 

Based off our conversation at last week's AST meeting, [here ](https://docs.google.com/document/d/1CnwPxkJT9nIkurAo1SCOcOaH_i-fAEMKeHwf1l6zVZ0/edit)is a **draft** communications plan for coordinating trawling efforts between Lasker, Shimada, and Lisa Marie. I've listed a couple of 'to do' items under each method to share where we are at so far with figuring out the best method. Please take a moment to review. I've tagged a couple people in some items for follow up. 

I think it will be helpful to have all of the vessels on the Saildrone Mission Portal, but it not yet clear if it will be obvious enough to see trawl locations with only GPS and we will likely want to know more than just position (haul catch size, size of hake catch, etc) to determine where to send RL for hake trawling. We have some figuring out to do with SCS, but if this could be an option...especially if we are able to visualize SCS data geographically. Last option is a simple google sheet. While this would require all parties to manually enter information, it is the most straightforward. 

Thanks! Feel free to add to the google doc with notes, comments, suggestions. 

Alice

**Comment by kstierhoff** [comment]
The trawl log was created and the entries have been updated here:
https://docs.google.com/spreadsheets/d/1w3n_tzzAKYeOjtsrPJN1shMOEBXFsw-j0zPG6FcXkx4/edit#gid=568685702
