### ISSUE TITLE
Write survey report

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#48]
TO-DO:

- [x] Get SCS data. In 2022 we used MOA Snap .elg files
- [x] Install Microsoft Access Database Engine so that I can access the Access trawl database
- [x] Get seine data. Need the "lm(lbc)_sets.csv", "lm(lbc)_catch.csv", and "lm_specimens.csv" files. In 2022, the LBC specimen data was included in the "lbc_catch.csv" file, but not sure that will be the same this year. Once obtain, set 'eval' equal to TRUE in the 'process-seine-data' chunk
- [x] Check about including processed Shimada data
- [ ] Check about including (U)CTD casts from LM and LBC
- [ ] Set 'eval' to TRUE for chunks 'calc-ns-transect-summaries' and 'plot-nearshore-figure' after nearshore data is obtained
- [ ] Update code to handle obtaining nav data for Leg 4 on Shimada, which would also be used for obtaining the static habitat images

**Comment by jrenfree** [comment]
Beginning writing of report. Currently only have data (some partial) for Lasker and Long Beach Carnage. Have data for Shimada but that might not be used in the final report.

**Comment by jrenfree** [comment]
Have a draft version that's ready for review. Checking with Kevin Hill on if Alex Jensen could be the technical reviewer.

**Comment by jrenfree** [comment]
Need to implement reviews from the following people:

- [x] Dave Demer
- [ ] LHP (Brad and Brittany)
- [ ] Bill Watson (currently addressed all his comments except for the section detailing northern stock migration, which might overlap with LHP's review)
- [x] Lanora

**Comment by kstierhoff** [comment]
Survey report has been published: https://repository.library.noaa.gov/view/noaa/61647
