### ISSUE TITLE
Prepare for meeting with industry partners on 9/25

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#49]
- [x] Map Lasker's CPS backscatter, egg distributions, and catch proportions  (optimally through Sunday, 9/24)
- [x] Map Shimada's CPS backscatter and hake backscatter
- [x] Map Lisa Marie's CPS backscatter and species proportions, separated by daytime and nighttime sets
- [x] Map Long Beach Carnage's CPS backscatter and species proportions (lower priority)
- [x] Determine the dates when we need the final species proportions and lengths, and age data, respectively, from LM

**Comment by jrenfree** [comment]
Here's the latest figure I have for Lasker, generated from reportSurvey:

![Image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/a1a8af43-35d6-419b-8055-1347c784b41c)

Latest plotSurvey can be found [here](https://drive.google.com/file/d/1thF56l2896dHnXCzeEoeuw66xv054-Tn/view?usp=drive_link).

Can update plotSurvey as possible after the Lasker departs for Leg 3.2 on 9/21.

**Comment by jrenfree** [comment]
Here's the map of CPS backscatter from the Shimada, taken from the interactive map generated by plotCSV_Shimada_2307_cps.Rmd, which can be found [here](https://drive.google.com/file/d/1XGr38f10dQXjukuyZE6I0yU2n4MUadM3/view?usp=drive_link).

![Image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/dbbee75f-286c-4d88-96fb-55b1df0b2359)

Below is the map of the 'hake' backscatter, which is calculated as the difference between the original NASC and the NASC attributed to CPS. The interactive map can be found [here](https://drive.google.com/file/d/14Dqt_nBy6Z06dxKg7kXyKKnkQ7teMQwh/view?usp=drive_link).

![Image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/cdc39524-cf98-46d2-a05b-639bbeb2ecc9)

**Comment by jrenfree** [comment]
Below is an image of the CPS NASC from the Long Beach Carnage. An interactive map can be found [here](https://drive.google.com/file/d/1crBENTET2jrgnhwqYcoxt2sPedvmx8pk/view?usp=drive_link).

![Image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/b542b2ae-d105-4056-a25b-7de47b019de1)

**Comment by kstierhoff** [comment]
> Here's the latest figure I have for Lasker, generated from reportSurvey:
> 
> ![Image](https://user-images.githubusercontent.com/8889568/269338651-a1a8af43-35d6-419b-8055-1347c784b41c.png)
> 
> Latest plotSurvey can be found [here](https://drive.google.com/file/d/1thF56l2896dHnXCzeEoeuw66xv054-Tn/view?usp=drive_link).
> 
> Can update plotSurvey as possible after the Lasker departs for Leg 3.2 on 9/21.

Latest version here, should be final for Leg 3:

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/2256746/7a93a1ce-9ee8-4d13-a4d2-3ac544636aa2)

**Comment by kstierhoff** [comment]
> Here's the map of CPS backscatter from the Shimada, taken from the interactive map generated by plotCSV_Shimada_2307_cps.Rmd, which can be found [here](https://drive.google.com/file/d/1XGr38f10dQXjukuyZE6I0yU2n4MUadM3/view?usp=drive_link).
> 
> ![Image](https://user-images.githubusercontent.com/8889568/269722335-dbbee75f-286c-4d88-96fb-55b1df0b2359.png)
> 
> Below is the map of the 'hake' backscatter, which is calculated as the difference between the original NASC and the NASC attributed to CPS. The interactive map can be found [here](https://drive.google.com/file/d/14Dqt_nBy6Z06dxKg7kXyKKnkQ7teMQwh/view?usp=drive_link).
> 
> ![Image](https://user-images.githubusercontent.com/8889568/270034950-cdc39524-cf98-46d2-a05b-639bbeb2ecc9.png)

Here is a revised plot of CPS backscatter from Shimada:
![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/2256746/546c7232-59d1-4de7-b144-184dad2884e6)

**Comment by kstierhoff** [comment]
> Below is an image of the CPS NASC from the Long Beach Carnage. An interactive map can be found [here](https://drive.google.com/file/d/1crBENTET2jrgnhwqYcoxt2sPedvmx8pk/view?usp=drive_link).
> 
> ![Image](https://user-images.githubusercontent.com/8889568/270038392-b542b2ae-d105-4056-a25b-7de47b019de1.png)

Here is an updated map of LBC backscatter after nascR processing:

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/2256746/aaab6dec-f43d-4c6e-8934-33a9b0e62ba7)

**Comment by kstierhoff** [comment]
Here is a plot of Lisa Marie backscatter following nascR processing.

Interactive maps can be found in [Google Drive](https://drive.google.com/drive/folders/1ZOv3hFg4S3TPsQsrCtt_yQeayinnRJCC?usp=drive_link).

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/2256746/ecd9c436-1de8-4095-bf77-31aec3571644)

**Comment by kstierhoff** [comment]
> > Below is an image of the CPS NASC from the Long Beach Carnage. An interactive map can be found [here](https://drive.google.com/file/d/1crBENTET2jrgnhwqYcoxt2sPedvmx8pk/view?usp=drive_link).
> > ![Image](https://user-images.githubusercontent.com/8889568/270038392-b542b2ae-d105-4056-a25b-7de47b019de1.png)
> 
> Here is an updated map of LBC backscatter after nascR processing:
> 
> ![image](https://user-images.githubusercontent.com/2256746/270136151-aaab6dec-f43d-4c6e-8934-33a9b0e62ba7.png)

Ok, here is one more plot of CPS backscatter from Long Beach Carnage, with the same extent as all other vessels for ease of comparison. Interactive maps can be found in [Google Drive](https://drive.google.com/drive/folders/1ZOv3hFg4S3TPsQsrCtt_yQeayinnRJCC?usp=drive_link).

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/2256746/c3bcb4e9-ad7d-4eb1-a9a0-c1ae5f0d7fc6)
