### ISSUE TITLE
Obtain catch data from Long Beach Carnage

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#54]

**Comment by jrenfree** [comment]
Need to obtain both set and specimen data

**Comment by kstierhoff** [comment]
Set information has been entered in the following Google Sheet from the scanned bucket sample sheets provided by Joel van Noord. 

https://docs.google.com/spreadsheets/d/1LdEnwL62ySTDjSd9hLZscqSyGlucUniydj60yctCuZc/edit#gid=0

We have also received some set and catch data from CDFW, but the formatting is confusing and awkward, so will try to use the data I generated in the meantime.

**Comment by kstierhoff** [comment]
Set and catch data from LBC are not available in AST4 (//swc-storage4-s/AST4/SURVEYS/20230708_CARNAGE_SummerCPS/DATA/SEINE/lbc_data_2307RL.xlsx). Still waiting for specimen data to finish processing. This will replace the Google Sheet mentioned previously.

**Comment by kstierhoff** [comment]
Specimen data are now available on AST4 ((//swc-storage4-s/AST4/SURVEYS/20230708_CARNAGE_SummerCPS/DATA/SEINE/lbc_data_2307RL.xlsx, specimens tab).
