### ISSUE TITLE
Generate animated habitat map

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#57]

**Comment by jrenfree** [comment]
Code is in place, but will need to re-run it after Leg 4.2 is complete. May also want to re-arrange the colors and remove the Shimada hake survey data.

**Comment by kstierhoff** [comment]
Since the Shimada/hake data (likely) won't be used to estimate the official biomass, I agree with the plan to remove those data from the animation.
