### ISSUE TITLE
Download Saildrone Data

### ISSUE THREAD

**Issue by kstierhoff** [nmfs-swfsc-ast/ast-tasks#58]
Download all Saildrone data from FTP.

- [x] SD-1048
- [x] SD-1060
- [x] SD-1096

**Comment by alicebeittel** [comment]
Hi Kevin, @jrenfree has been the one responsible for downloading the Saildrone data from FTP and managing the locations of Saildrone data on the server.

**Comment by kstierhoff** [comment]
Thanks for letting me know, I just updated the assignee.

**Comment by jrenfree** [comment]
Yeah I’ll take care of this on Monday. We’ll be occupied enough with the
SD-1060 processing in the meantime.

**Comment by kstierhoff** [comment]
Per [Josiah's comment on this issue](https://github.com/nmfs-swfsc-ast/ast-tasks/issues/52#issuecomment-1830355849), all SD data have been downloaded to AST4.
