### ISSUE TITLE
Compute biomass estimates

### ISSUE THREAD

**Issue by kstierhoff** [nmfs-swfsc-ast/ast-tasks#60]

**Comment by kstierhoff** [comment]
- [x] Set stock break at Bodega Bay for NS sardine transects
- [ ] Create ECDF plots of biomass relative to time since the nearest trawl cluster, similar to what's done for distance in the core region.
- [ ] Create ECDF plots of biomass relative to distance from the nearest trawl cluster, similar to what's done in the core region.
- [x] Include Saildrone transect data and re-compute biomass.
- [x] Trim nearshore backscatter intervals using a polygon surrounding the planned nearshore transects.
- [x] Remove offshore purse seine sets from LM data set. Use polygon surrounding planned nearshore transects to exclude sets. 
- [x] Examine calibration results/ECS files for Saildrone and Shimada in S Oregon where sardine biomass is greatest @jrenfree 
- [x] Compare s_V within fish schools between SH and SD off Oregon
- [x] Add positive seine clusters (blue numbers) to nearshore biomass density plots for each species
- [ ] Generate purse seine plots using plotSeine_2307RL (or generic version)

**Comment by jrenfree** [comment]
Will focus on Transect 118, sampled by SD-1060:

![2307SD1060_118_CPS-38 Remove Passive Pings](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/4db17b08-58da-4309-9bfd-3a04b7522521)

We conducted a pre- and post-survey calibration, which resulted in the following for 38 kHz

| Parameter | PRE | POST |
| ----------- | ---- | ------ |
| Gain | 19.04 | 19.10 |
| BW_along | 17.8 | 17.9 |
| BW_athwt | 17.8 | 17.9 |
| Offset_along | 0.2 | 0.2 |
| Offset_athwt | -0.6 | -0.9 |
| EBA | -12.6 | -12.6 |
| Sa_corr | -0.04 | 0.03 |
| RMS | 0.16 | 0.13 |

So both were very similar, and we applied the Pre-survey results for the data processing. The template ECS file appears to have the correct environment and calibration parameters entered:

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/37671431-6dd0-457f-b805-bbf620054fb1)

The CTD cast used to process this transect was cast 158 from the Shimada hake survey, which appeared to have a harmonic sound speed of 1495.67 m/s, which matches with what's in the ECS file used to process this transect:

![image](https://github.com/nmfs-swfsc-ast/ast-tasks/assets/8889568/91f77d84-e40d-48d5-ba90-e8dad8a1a49e)

The calibration parameters in the ECS value are from the template file but compensated by change in sound speeds. With a calibration (template) sound speed of 1501.37 and transect sound speed of 1495.67, my calculations are:

| Parameter | Template | Transect |
| ----------- | ---------- | --------- |
| Gain          |    19.04    |  19.073  |
| EBA           |    -12.6    |  -12.633  |
| BW_along | 17.8         | 17.7324  |
| BW_athwt  | 17.8         | 17.7324  |

This matches what's in the transect ECS file, so looks like it's being compensated correctly.

So unless both calibrations were way off for this echosounder, I think this checks out just fine. Suppose the question then becomes if the scatterers near the seabed are indeed CPS.

**Comment by kstierhoff** [comment]
Compelling and thorough analysis. I think we can consider that item completed and debunked.

**Comment by kstierhoff** [comment]
Final biomass estimates computed for all species/stocks, after accounting for deep backscatter from CSNA in the nearshore region of the SCB. Results incorporated into biomass report.
