### ISSUE TITLE
Create documentation for handling net mensuration

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#63]
Brad recommended that we create documentation to identify what tasks need to be done regarding net mensuration, and who will do them. A lot of the procedural documentation was created during the MFT survey, but we will need to figure out who will be in charge of what and if any additional duties will need to be added to the sampling protocols.

**Comment by kstierhoff** [comment]
Is this done? If so, should be closed.

**Comment by jrenfree** [comment]
Meh, there isn't an official SOP per se, but the original document I made contains a lot of the necessary info, and there weren't any issues with operations this year, so I think we're good for now.
