### ISSUE TITLE
Obtain Mexico permit

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#69]

**Comment by jrenfree** [comment]
As of 2/27/2024 there is no update from the Mexican government

**Comment by kstierhoff** [comment]
As of May 22 (per email from @stevesessions), 6 out of 7 agencies have approved.  Awaiting CONAPESCA approval.

SEMARNAT has granted approval given the following conditions.  My concerns are the highlighted,  Final Report hard and electronic copies 30 days after completion of survey... in Mexico!

@kstierhoff will follow-up regarding SEMARNAT's request for hard copy reports.
