### ISSUE TITLE
Foreign National Requests

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#71]
FNRs are due by 5/8/24

**Comment by jrenfree** [comment]
@kstierhoff have you received any word back from IMIPAS on someone sailing on Leg 1? If so we should get started on the foreign national paperwork soon(ish).

**Comment by kstierhoff** [comment]
I have not, so we need to follow up.

Kevin L. Stierhoff

Research Fisheries Biologist, NOAA/NMFS/SWFSC

NOAA Fisheries | U.S. Department of Commerce

Office: (831) 420-3919

www.fisheries.noaa.gov

**Comment by jrenfree** [comment]
Mario Vásquez Ortiz and Daniel Hernández Cruz will be sailing on Leg 1, so we will need to submit foreign national requests. Kevin, is that something I can do or do you have to do it through the FNRS system?

**Comment by kstierhoff** [comment]
I will do this via the FNRS system.

**Comment by jrenfree** [comment]
Cool, thanks. Just let me know if there's anything I can do. I looked at the 2022 survey folder and there were a number of forms that need to be signed, but perhaps that's been simplified with the FNRS system.

**Comment by kstierhoff** [comment]
There are numerous forms, and Dave has documented the process pretty well. I did this for the first time last summer, and will begin chipping away at the documents for this year.

TO DO: 
Prepare documents for:
Mario:
- [x] DAO 207-12
- [x] OMAO Form
- [x] Invitation Letter - SWFSC
- [x] Invitation Letter - FRD
- [x] Consulate Letter of Support

Daniel:
- [x] DAO 207-12
- [x] OMAO Form
- [x] Invitation Letter - SWFSC
- [x] Invitation Letter - FRD
- [x] Consulate Letter of Support

Working forms here: \\swc-storage4-s\AST5\SURVEYS\20240708_LASKER_SummerCPS\DOCUMENTS\Visiting Scientist Forms

**Comment by kstierhoff** [comment]
Consulate letters of support have been sent to IMIPAS. Invitation letters from FRD have been sent to Annie for signature, and SWFSC memo sent to Annie for Kristen's signature. Next steps include:

- [x] Send Invitation Letters to IMIPAS
- [x] Send OMAO forms to OMAO
- [x] Send DAO forms to FN guests for signature
- [x] Prepare DRAFT guest applications in FNRS
- [x] Add OMAO and DAO forms to FNRS applications
- [x] Submit FN Guest applications to FNRS 

FN applications must be submitted 30d in advance, but must also be submitted while on site (I think). Can't do on VPN, so I will submit these on Monday.

**Comment by kstierhoff** [comment]
Signed OMAO access memos rec'd from CDR Barry and uploaded to FNRS. Guest Requests submitted for final approval.
