### ISSUE TITLE
Determine ME70 configuration

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#75]
We need to decide what ME70 settings we want for the 2024 CPS Survey, namely the beam configuration. Yoann is willing to look at the existing beam configurations and help us decide based on our analysis goals. So next step will be to sent our beam configuration to Yoann and initiate a discussion with him.

**Comment by kstierhoff** [comment]
The survey is over, and thus this should be closed.
