### ISSUE TITLE
QA/QC Lisa Marie Acoustic Data

### ISSUE THREAD

**Issue by alicebeittel** [nmfs-swfsc-ast/ast-tasks#91]
AST,
I've updated the output from plotCSV for Lisa Marie:
https://rpubs.com/kstierhoff/1222874

If you've been processing data in Echoview (and nascR), please take a look. There are some transects that will need to be trimmed to remove extraneous ends, etc. This output only contains files resulting from the nascR processing, so won't show any transects that have only been processed in Echoview.

Thanks,
Kevin

**Comment by kstierhoff** [comment]
According to the [EV Processing log](https://docs.google.com/spreadsheets/d/1UybPB_wSoHCYujqGyCAZKe4tAkRbVl30_4aQ233kh5M/edit?gid=1639940210#gid=1639940210), LM review has been completed. Can reopen as needed.
