### ISSUE TITLE
Write Leg 2 summary

### ISSUE THREAD

**Issue by jrenfree** [nmfs-swfsc-ast/ast-tasks#98]
Need to add a Leg 2 summary to the following document:

https://docs.google.com/document/d/1e-Au9vELo3uee3-ndaKE734nNI0uzwNQphA-l64Ck_I/edit?usp=sharing

**Comment by kstierhoff** [comment]
I drafted a summary for Leg 2. @alicebeittel please review. Green book pages are available here: \\swc-storage4-s\AST5\SURVEYS\20240625_LASKER_SummerCPS\DOCUMENTS\2407RL - Green Book Leg 2.pdf

**Comment by alicebeittel** [comment]
Thanks Kevin! I didn't realize this was missing. Commented on the google
doc. Looks good.


LT Alice Beittel, NOAA Corps (she/her)
Acting SWFSC Planning Officer / Advanced Survey Technology Officer
NOAA Southwest Fisheries Science Center
8901 La Jolla Shores Drive
San Diego, CA 92037
Google Voice: (858) 546-5671
Cell: (510) 847-2048

**Comment by kstierhoff** [comment]
Considering this done. Will continue editing in the Google Doc, or directly in the biomass report.
